kube-prometheus-stack:
  prometheus:
    prometheusSpec:
      ## Discover all ServiceMonitors/PodMonitors regardless of labels
      serviceMonitorSelectorNilUsesHelmValues: false
      podMonitorSelectorNilUsesHelmValues: false
      ruleSelectorNilUsesHelmValues: false
      retention: 15d

  grafana:
    enabled: true
    sidecar:
      dashboards:
        enabled: true
        searchNamespace: ALL
    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: ca-issuer
      hosts:
        - grafana.example.com
      tls:
        - secretName: grafana-tls
          hosts:
            - grafana.example.com

  alertmanager:
    enabled: true
