argo-cd:
  server:
    replicas: 1
    ingress:
      enabled: true
      ingressClassName: traefik
      hostname: argocd.dev.example.com
      tls: true

  controller:
    replicas: 1

  repoServer:
    replicas: 1

  redis-ha:
    enabled: false

  configs:
    cm:
      timeout.reconciliation: "60s"               # Faster reconciliation in dev
